### ISSUE TITLE
Data in observable notebook and supporting CSVs appears truncated to last day

### ISSUE THREAD

**Issue by adamjsimon** [rdmurphy/actblue-ticker-tracker#1]
It looks like the scripts are only maintaining one day's worth of data.

**Comment by rdmurphy** [comment]
Hello! Yes I've noticed this as well — something is up with the script that generates the CSV now that we're in 2021, and I'm still trying to sort out why. 🤔 But the data *is* still there and being tracked! (I use the git history of that file with a single number to "track" it.) So once I sort that out there won't be any missing times.

**Comment by rdmurphy** [comment]
Finally sorted this out. It is fixed. Thanks for filing the issue!

**Comment by adamjsimon** [comment]
@rdmurphy thanks for fixing this so quickly! I know this is mostly a side project for you but it's pretty cool and does the job well! Thanks for your work on this!
